/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.main;

import java.awt.event.KeyEvent;

/**
 *
 * @author Alejandro P
 */
public class VentanaForm extends javax.swing.JFrame {

    private Mercado tienda;
    Productos prod = new Productos();
    /**
     * Creates new form VentanaForm
     */
    public VentanaForm() {
        initComponents();
        tienda = new Mercado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaCliente = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        btn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnIngresarCliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        lblClientes1 = new javax.swing.JLabel();
        lblSaldo1 = new javax.swing.JLabel();
        lblAtendidos1 = new javax.swing.JLabel();
        lblClientes2 = new javax.swing.JLabel();
        lblSaldo2 = new javax.swing.JLabel();
        lblAtendidos2 = new javax.swing.JLabel();
        lblClientes3 = new javax.swing.JLabel();
        lblSaldo3 = new javax.swing.JLabel();
        lblAtendidos3 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jLabel19 = new javax.swing.JLabel();
        lblClientes4 = new javax.swing.JLabel();
        lblSaldo4 = new javax.swing.JLabel();
        lblAtendidos4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        btnAtender4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnAtender1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnAtender2 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnAtender3 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("Nombre:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("Caja:");
        jLabel17.setToolTipText("");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setText("Total a Pagar:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        txtNombre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 199, -1));

        txtValor.setEditable(false);
        txtValor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtValor.setText("0");
        jPanel2.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 199, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Ingresar Cliente");
        jButton1.setActionCommand("btnIngresarCliente2");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 199, 50));

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 40, -1));

        btn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn.setText("Leche");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        jPanel2.add(btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 100, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton3.setText("Arroz");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 90, -1));

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton4.setText("Frijoles");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 110, -1));

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton5.setText("Bistec Cerdo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 100, -1));

        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton6.setText("Tomate");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 90, -1));

        jButton7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton7.setText("Coca Cola");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 110, -1));

        jButton8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton8.setText("Ranchita");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 100, -1));

        jButton9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton9.setText("Fideos");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 90, -1));

        jButton10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton10.setText("Fresca");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 110, -1));

        jButton11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton11.setText("Huevos");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 100, -1));

        jButton12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton12.setText("Chayote");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 90, -1));

        jButton13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton13.setText("Cebolla");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 110, -1));

        jButton14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton14.setText("Cacique");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 100, -1));

        jButton15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton15.setText("Pilsen");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 90, -1));

        jButton16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton16.setText("Flor de Caña");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 110, -1));

        btnEliminar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar Último Producto");
        btnEliminar.setToolTipText("");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel15.setText("Ingresar Cliente");

        javax.swing.GroupLayout VentanaClienteLayout = new javax.swing.GroupLayout(VentanaCliente.getContentPane());
        VentanaCliente.getContentPane().setLayout(VentanaClienteLayout);
        VentanaClienteLayout.setHorizontalGroup(
            VentanaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VentanaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
                    .addGroup(VentanaClienteLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        VentanaClienteLayout.setVerticalGroup(
            VentanaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaClienteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIngresarCliente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnIngresarCliente.setText("Ingresar Cliente");
        btnIngresarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 160, 70));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Supermercado El Troyano");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        lblSaldo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSaldo.setText("$0");
        jPanel1.add(lblSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Caja 1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Caja 2");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Caja 4");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, -1, -1));

        jList3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jScrollPane6.setViewportView(jList3);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 130, -1));

        lblClientes1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblClientes1.setText("$0");
        jPanel1.add(lblClientes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        lblSaldo1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblSaldo1.setText("$0");
        jPanel1.add(lblSaldo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        lblAtendidos1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblAtendidos1.setText("$0");
        jPanel1.add(lblAtendidos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, -1, -1));

        lblClientes2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblClientes2.setText("$0");
        jPanel1.add(lblClientes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, -1, -1));

        lblSaldo2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblSaldo2.setText("$0");
        jPanel1.add(lblSaldo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, -1));

        lblAtendidos2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblAtendidos2.setText("$0");
        jPanel1.add(lblAtendidos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, -1, -1));

        lblClientes3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblClientes3.setText("$0");
        jPanel1.add(lblClientes3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, -1, -1));

        lblSaldo3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblSaldo3.setText("$0");
        jPanel1.add(lblSaldo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, -1, -1));

        lblAtendidos3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblAtendidos3.setText("$0");
        jPanel1.add(lblAtendidos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, -1, -1));

        jList4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jScrollPane7.setViewportView(jList4);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, 130, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setText("Caja 3");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, -1, -1));

        lblClientes4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblClientes4.setText("$0");
        jPanel1.add(lblClientes4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 280, -1, -1));

        lblSaldo4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblSaldo4.setText("$0");
        jPanel1.add(lblSaldo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 310, -1, -1));

        lblAtendidos4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblAtendidos4.setText("$0");
        jPanel1.add(lblAtendidos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 340, -1, -1));

        jList1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jScrollPane4.setViewportView(jList1);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 130, -1));

        jList2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jScrollPane5.setViewportView(jList2);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 130, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Atendidos:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        btnAtender4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAtender4.setText("Atender");
        btnAtender4.setActionCommand("Atender3");
        btnAtender4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtender4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtender4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 380, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Atendidos:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Saldo:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Clientes:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Atendidos:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Saldo:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Clientes:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 280, -1, -1));

        btnAtender1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAtender1.setText("Atender");
        btnAtender1.setActionCommand("Atender1");
        btnAtender1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtender1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtender1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Clientes:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));
        jLabel6.getAccessibleContext().setAccessibleName("");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setText("Atendidos:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, -1, -1));

        btnAtender2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAtender2.setText("Atender");
        btnAtender2.setActionCommand("Atender2");
        btnAtender2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtender2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtender2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, -1, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel21.setText("Saldo:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Saldo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        btnAtender3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAtender3.setText("Atender");
        btnAtender3.setActionCommand("Atender3");
        btnAtender3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtender3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtender3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, -1, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel22.setText("Clientes:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Saldo Total:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarClienteActionPerformed
        this.VentanaCliente.setVisible(true);
        this.VentanaCliente.setSize(800, 500);
    }//GEN-LAST:event_btnIngresarClienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tienda.ingresarCliente(new Cliente(txtNombre.getText(), Integer.parseInt(jComboBox1.getSelectedItem().toString()), Float.parseFloat(txtValor.getText())));
        tienda.imprimir(jList1, jList2, jList3, jList4);
        tienda.mostrarCuentas(lblClientes1, lblClientes2, lblClientes3, lblClientes4);
        tienda.mostrarSaldos(lblSaldo1, lblSaldo2, lblSaldo3, lblSaldo4);

        this.VentanaCliente.setVisible(false);
        txtNombre.setText("");
        txtValor.setText("0");
        jComboBox1.setSelectedItem("Caja 1");
        lblSaldo.setText("$" + tienda.calcularSaldo());

        int n = prod.len();
        for (int i = 0; i < n; i++) {
            prod.extraer();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAtender1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtender1ActionPerformed
        tienda.atender1(lblAtendidos1);
        tienda.imprimir(jList1, jList2, jList3, jList4);
        lblClientes1.setText(String.valueOf(Integer.parseInt(lblClientes1.getText())-1));
    }//GEN-LAST:event_btnAtender1ActionPerformed

    private void btnAtender2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtender2ActionPerformed
        tienda.atender2(lblAtendidos2);
        tienda.imprimir(jList1, jList2, jList3, jList4);
        lblClientes2.setText(String.valueOf(Integer.parseInt(lblClientes2.getText())-1));
    }//GEN-LAST:event_btnAtender2ActionPerformed

    private void btnAtender4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtender4ActionPerformed
        tienda.atender4(lblAtendidos4);
        tienda.imprimir(jList1, jList2, jList3, jList4);
        lblClientes4.setText(String.valueOf(Integer.parseInt(lblClientes4.getText())-1));
    }//GEN-LAST:event_btnAtender4ActionPerformed

    private void btnAtender3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtender3ActionPerformed
        tienda.atender3(lblAtendidos3);
        tienda.imprimir(jList1, jList2, jList3, jList4);
        lblClientes3.setText(String.valueOf(Integer.parseInt(lblClientes3.getText())-1));
    }//GEN-LAST:event_btnAtender3ActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        prod.insertar("Leche", 1150);
        this.txtValor.setText(String.valueOf(prod.pagototal()));
    }//GEN-LAST:event_btnActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        prod.extraer();
        this.txtValor.setText(String.valueOf(prod.pagototal()));
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        prod.insertar("Arroz", 2150);
        this.txtValor.setText(String.valueOf(prod.pagototal()));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        prod.insertar("Frijoles", 1900);
        this.txtValor.setText(String.valueOf(prod.pagototal()));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        prod.insertar("Bistec de Cerdo", 3000);
        this.txtValor.setText(String.valueOf(prod.pagototal()));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        prod.insertar("Tomate", 450);
        this.txtValor.setText(String.valueOf(prod.pagototal()));
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        prod.insertar("Coca Cola", 750);
        this.txtValor.setText(String.valueOf(prod.pagototal()));
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        prod.insertar("Ranchita", 100);
        this.txtValor.setText(String.valueOf(prod.pagototal()));
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        prod.insertar("Fideos", 1750);
        this.txtValor.setText(String.valueOf(prod.pagototal()));
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        prod.insertar("Fresca", 2000);
        this.txtValor.setText(String.valueOf(prod.pagototal()));
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        prod.insertar("Huevos", 2500);
        this.txtValor.setText(String.valueOf(prod.pagototal()));
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        prod.insertar("Chayote", 900);
        this.txtValor.setText(String.valueOf(prod.pagototal()));
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        prod.insertar("Cebolla", 450);
        this.txtValor.setText(String.valueOf(prod.pagototal()));
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        prod.insertar("Cacique", 5000);
        this.txtValor.setText(String.valueOf(prod.pagototal()));
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        prod.insertar("Pilsen", 1200);
        this.txtValor.setText(String.valueOf(prod.pagototal()));
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        prod.insertar("Flor de Caña", 7450);
        this.txtValor.setText(String.valueOf(prod.pagototal()));
    }//GEN-LAST:event_jButton16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame VentanaCliente;
    private javax.swing.JButton btn;
    private javax.swing.JButton btnAtender1;
    private javax.swing.JButton btnAtender2;
    private javax.swing.JButton btnAtender3;
    private javax.swing.JButton btnAtender4;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIngresarCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblAtendidos1;
    private javax.swing.JLabel lblAtendidos2;
    private javax.swing.JLabel lblAtendidos3;
    private javax.swing.JLabel lblAtendidos4;
    private javax.swing.JLabel lblClientes1;
    private javax.swing.JLabel lblClientes2;
    private javax.swing.JLabel lblClientes3;
    private javax.swing.JLabel lblClientes4;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblSaldo1;
    private javax.swing.JLabel lblSaldo2;
    private javax.swing.JLabel lblSaldo3;
    private javax.swing.JLabel lblSaldo4;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
